-- ============================================================
-- 2302 - Esquema completo para Supabase
-- Ejecutá este archivo en Supabase → SQL Editor (todo de una vez o por bloques).
--
-- Cómo usar:
-- 1. Entrá a tu proyecto en supabase.com → SQL Editor.
-- 2. Pegá y ejecutá este script completo (Run).
-- 3. Si ya tenés tablas, los CREATE TABLE IF NOT EXISTS no las borran;
--    las secciones 5 y 6 agregan columnas y políticas si faltan.
--
-- AVISO DE SUPABASE "Query has destructive operations":
-- El script usa DROP POLICY IF EXISTS y DROP CONSTRAINT IF EXISTS solo para
-- reemplazar política y constraint por versiones actualizadas. NO borra tablas
-- ni datos. Es seguro hacer clic en "Run this query".
-- ============================================================

-- --------------------------------------------------------------
-- 1. CATEGORÍAS (panel admin: categorías de productos)
-- --------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.categorias (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL,
  slug text NOT NULL UNIQUE
);

-- Categorías iniciales (opcional)
INSERT INTO public.categorias (nombre, slug) VALUES
  ('Rostro', 'face'),
  ('Cuerpo', 'body'),
  ('Cabello', 'hair')
ON CONFLICT (slug) DO NOTHING;


-- --------------------------------------------------------------
-- 2. PRODUCTOS (tienda + panel admin)
-- Columnas con espacio van entre comillas dobles en PostgreSQL.
-- --------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.productos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL DEFAULT '',
  precio numeric(12,2) NOT NULL DEFAULT 0,
  imagen_url text DEFAULT '',
  categoria text NOT NULL DEFAULT 'face',
  tamaño text DEFAULT '',
  "descripcion corta" text DEFAULT '',
  "descripcion completa" text DEFAULT '',
  ingredientes text DEFAULT '',
  "modo de uso" text DEFAULT '',
  popular boolean NOT NULL DEFAULT false,
  offer boolean NOT NULL DEFAULT false,
  precio_oferta numeric(12,2) DEFAULT null,
  section_visibility jsonb DEFAULT '{"showDescription":true,"showShortDescription":true,"showSize":true,"showIngredients":true,"showHowToUse":true}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_productos_categoria ON public.productos (categoria);
CREATE INDEX IF NOT EXISTS idx_productos_id ON public.productos (id DESC);


-- --------------------------------------------------------------
-- 3. COLECCIÓN (tarjetas de la sección Colección en la home)
-- --------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.coleccion (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo text NOT NULL DEFAULT '',
  imagen_url text NOT NULL DEFAULT '',
  link text DEFAULT '',
  descripcion text DEFAULT '',
  orden integer NOT NULL DEFAULT 0,
  activo boolean NOT NULL DEFAULT true
);

CREATE INDEX IF NOT EXISTS idx_coleccion_orden ON public.coleccion (orden, id);


-- --------------------------------------------------------------
-- 4. PEDIDOS / VENTAS (checkout + Mercado Pago + panel admin)
-- El id debe ser identity para que INSERT devuelva el id al crear.
-- --------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.pedidos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_nombre text NOT NULL,
  cliente_email text NOT NULL,
  cliente_telefono text NOT NULL,
  direccion text NOT NULL,
  localidad text NOT NULL,
  cp text,
  comentarios text,
  items jsonb DEFAULT '[]'::jsonb,
  total numeric(12,2) DEFAULT 0,
  estado text NOT NULL DEFAULT 'pendiente_pago'
    CHECK (estado IN ('pendiente_pago', 'pagado', 'enviado', 'cancelado')),
  created_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_pedidos_created_at ON public.pedidos (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_pedidos_estado ON public.pedidos (estado);

-- RLS: el backend usa service_role y bypasea RLS. Por si usás anon en algún flujo:
ALTER TABLE public.pedidos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Service role full access" ON public.pedidos;
CREATE POLICY "Allow service role full access on pedidos"
  ON public.pedidos FOR ALL
  USING (true)
  WITH CHECK (true);


-- --------------------------------------------------------------
-- 5. AGREGAR COLUMNAS SI LAS TABLAS YA EXISTÍAN (ejecutar solo si hace falta)
-- --------------------------------------------------------------

-- Productos: precio oferta
ALTER TABLE public.productos
  ADD COLUMN IF NOT EXISTS precio_oferta numeric(12,2) DEFAULT null;

-- Productos: visibilidad de secciones (admin)
ALTER TABLE public.productos
  ADD COLUMN IF NOT EXISTS section_visibility jsonb DEFAULT '{"showDescription":true,"showShortDescription":true,"showSize":true,"showIngredients":true,"showHowToUse":true}'::jsonb;

-- Productos: columnas con espacios si no existen (PostgreSQL 11+)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'productos' AND column_name = 'descripcion corta') THEN
    ALTER TABLE public.productos ADD COLUMN "descripcion corta" text DEFAULT '';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'productos' AND column_name = 'descripcion completa') THEN
    ALTER TABLE public.productos ADD COLUMN "descripcion completa" text DEFAULT '';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'productos' AND column_name = 'modo de uso') THEN
    ALTER TABLE public.productos ADD COLUMN "modo de uso" text DEFAULT '';
  END IF;
END $$;

-- Pedidos: asegurar constraint de estado con 'cancelado'
ALTER TABLE public.pedidos DROP CONSTRAINT IF EXISTS pedidos_estado_check;
ALTER TABLE public.pedidos ADD CONSTRAINT pedidos_estado_check
  CHECK (estado IN ('pendiente_pago', 'pagado', 'enviado', 'cancelado'));


-- --------------------------------------------------------------
-- 6. PERMISOS (opcional: que la API con service_role pueda todo)
-- Por defecto el rol service_role ya tiene acceso. Esto es por si usás anon.
-- --------------------------------------------------------------
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT ON public.categorias TO anon, authenticated;
GRANT SELECT ON public.productos TO anon, authenticated;
GRANT SELECT ON public.coleccion TO anon, authenticated;
GRANT ALL ON public.pedidos TO service_role;
GRANT ALL ON public.categorias TO service_role;
GRANT ALL ON public.productos TO service_role;
GRANT ALL ON public.coleccion TO service_role;

-- Secuencias para identity (por si algo falla al insertar)
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;
