-- Ejecuta este SQL en el editor SQL de tu proyecto Supabase (SQL Editor)
-- para crear la tabla de categorías (editables desde el panel admin).

CREATE TABLE IF NOT EXISTS categorias (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL,
  slug text NOT NULL UNIQUE
);

-- Categorías iniciales (slug = valor que se guarda en productos.categoria)
INSERT INTO categorias (nombre, slug) VALUES
  ('Rostro', 'face'),
  ('Cuerpo', 'body'),
  ('Cabello', 'hair')
ON CONFLICT (slug) DO NOTHING;
