-- Ejecuta este SQL en el editor SQL de tu proyecto Supabase (SQL Editor)
-- para crear la tabla de tarjetas de la sección Colección (editable desde el panel admin).

CREATE TABLE IF NOT EXISTS coleccion (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo text NOT NULL DEFAULT '',
  imagen_url text NOT NULL DEFAULT '',
  link text DEFAULT '',
  descripcion text DEFAULT '',
  orden integer NOT NULL DEFAULT 0,
  activo boolean NOT NULL DEFAULT true
);

-- Índice para ordenar por orden y id
CREATE INDEX IF NOT EXISTS idx_coleccion_orden ON coleccion (orden, id);

-- Comentario: las tarjetas se muestran en la sección "Colección" de la página principal.
-- El panel admin (/admin-panel.html) permite crear, editar y eliminar tarjetas.
-- orden: menor número = aparece primero. activo: false = no se muestra en la home.
