-- Ejecuta este SQL en Supabase (SQL Editor) para crear la tabla de pedidos/ventas.
-- Así el panel admin puede listar pedidos y marcar: pendiente de pago → pagado → enviado.

create table if not exists public.pedidos (
  id bigint generated by default as identity primary key,
  cliente_nombre text not null,
  cliente_email text not null,
  cliente_telefono text not null,
  direccion text not null,
  localidad text not null,
  cp text,
  comentarios text,
  items jsonb default '[]'::jsonb,
  total numeric(12,2) default 0,
  estado text not null default 'pendiente_pago' check (estado in ('pendiente_pago', 'pagado', 'enviado')),
  created_at timestamptz default now()
);

-- Índice para listar por fecha
create index if not exists idx_pedidos_created_at on public.pedidos (created_at desc);

-- RLS: permitir que el backend (service_role) haga todo; anon no puede leer pedidos.
alter table public.pedidos enable row level security;

create policy "Service role full access"
  on public.pedidos for all
  using (true)
  with check (true);
